---
__cockpit_packages_minimal:
  - cockpit-system
  - cockpit-ws
__cockpit_packages_default:
  - cockpit-bridge
  - cockpit-networkmanager
  - cockpit-selinux
  - cockpit-storaged
__cockpit_packages_full:
  - cockpit-bridge
  - cockpit-networkmanager
  - cockpit-podman
  - cockpit-selinux
  - cockpit-storaged
  - cockpit-tukit
__cockpit_packages:
  minimal: "{{ __cockpit_packages_minimal }}"
  default: "{{ __cockpit_packages_minimal + __cockpit_packages_default }}"
  full: "{{ __cockpit_packages_minimal + __cockpit_packages_default + __cockpit_packages_full }}"
