---
- name: Restore create_user.yml/create_user2.yml
  hosts: all
  vars_files:
    - secret2.yml
  tasks:
    - name: Secret 사용한 user1 사용자 추가
      ansible.builtin.user:
        name: "{{ username }}"
        state: absent
