---
- name: 사용자 정의 팩트를 사용한 웹 서버 설정
  hosts: all
  gather_facts: true
  tasks:
    - name: 3) 방화벽 등록 - {{ ansible_local.custom.general.fwsvc }}
      ansible.posix.firewalld:
        service: "{{ ansible_local.custom.general.fwsvc }}"
        permanent: true
        immediate: true
        state: disabled

    - name: 2) 서비스 종료 - {{ ansible_local.custom.general.service }}
      ansible.builtin.service:
        name: "{{ ansible_local.custom.general.service }}"
        enabled: false
        state: stopped

    - name: 1) 패키지 설치 - {{ ansible_local.custom.general.package }}
      ansible.builtin.dnf:
        name: "{{ ansible_local.custom.general.package }}"
        state: absent

    - name: 4) 팩트 삭제
      ansible.builtin.file:
        path: /etc/ansible/facts.d
        state: absent
