---
- name: 0) 작업 제어 실습
  hosts: all
  gather_facts: true
  vars_files:
    - vars/vars.yml
  tasks:
    - name: 0) 점검, (ㄱ)메모리 점검 (ㄴ)배포판 종류 점검
      ansible.builtin.fail:
        msg: "메모리가 256M 보다 작거나 CentOS가 아닙니다."
      when: >
        ansible_memtotal_mb < min_ram_mb or
        ansible_distribution != "CentOS"

    - name: 0) 다른 점검, (ㄷ)배포판 버전 점검
      ansible.builtin.debug:
        msg: "CentOS Stream 9버전에서만 동작합니다."
      failed_when: ansible_distribution_version != "9"

    - name: 1) 방화벽에 포트 제거 - {{ firewall_rules }}
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        immediate: true
        state: disabled
      loop: "{{ firewall_rules }}"

    - name: 2) 서비스 종료 - {{ services }}
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: false
        state: stopped
      loop: "{{ services }}"

    - name: 3) 웹 서비스 설정 삭제
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent

    - name: 4) 패키지 삭제 - {{ packages }}
      ansible.builtin.dnf:
        name:
          - httpd
          - mod_ssl
        state: absent
