---
- name: Install and start Apache HTTPD
  hosts: all
  gather_facts: false
  tasks:
    ###############################################
    # >>>> 팩트 변수를 사용하지 않는 플레이북 <<<<
    ###############################################
    # => gather_facts: true
    - name: httpd package is present
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Correct index.html is present
      ansible.builtin.copy:
        content: "Welcome to My Server.\n"
        dest: /var/www/html/index.html

    - name: httpd is started
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: firewalld is started
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

    - name: Configuration firewall
      ansible.posix.firewalld:
        service: http
        permanent: yes
        immediate: yes
        state: enabled

