---
- name: Restore factcheck.yml
  hosts: all
  gather_facts: false
  tasks:
    - name: 1) 방화벽 포트 제거
      ansible.posix.firewalld:
        service: http
        permanent: true
        immediate: true
        state: disabled

    - name: 2) 서비스 중지
      ansible.builtin.service:
        name: "{{ item }}"
        state: stopped
        enabled: false
      loop:
        - httpd
        - firewalld

    - name: 3) index.html 파일 삭제
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent

    - name: 4) 패키지 삭제
      ansible.builtin.yum:
        name: httpd
        state: absent
