---
- name: Restore playbook.yml
  hosts: all
  vars:
    web_package: httpd
    db_package: mariadb-server
    db_service: mariadb
  tasks:
    - name: Attepmt to set up a web server
      block:
        - name: 서비스 중지
          ansible.builtin.service:
            name: "{{ db_service }}"
            state: stopped
            enabled: false

        - name: 패키지 삭제
          ansible.builtin.yum:
            name:
              - "{{ web_package }}"
              - "{{ db_package }}"
            state: absent
      rescue:
        - name: 패키지 삭제 에러 메시지
          ansible.builtin.debug:
            msg: "[ fail ] 패키지 삭제가 되지 않습니다. - {{ web_package}} {{ db_package }}"

