---
- name: Restore_intranet.yml
  hosts: all
  tasks:
    - name: 방화벽 포트 제거 - http
      ansible.posix.firewalld:
        service: http
        permanent: true
        immediate: true
        state: disabled
      ignore_errors: true

    - name: 서비스 중지 - (service, systemd) httpd, firewalld
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
      loop:
        - httpd
        - firewalld

    - name: 파일 삭제 - (file) /var/www/html/index.html
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent  

    - name: 패키지 삭제- (yum, dnf) httpd
      ansible.builtin.dnf:
        name: httpd
        state: absent
