---
#################################################################
# Play1 - 웹 서버 설정
# * 1) 패키지 설치- httpd, mod_ssl, firewalld, python3-PyMySQL
# * 2) 서비스 설정- /var/www/html/index.html
# * 3) 서비스 기동 - httpd, firewalld
# * 4) 방화벽 등록 - http, https
# Play2 - 웹 서버 테스트
# * 1) 웹 요청 - http://192.168.10.11/
# * 2) 웹 출력 확인
#################################################################
# Play1: 웹 서버 설정
- name: Play1 - 웹 서버 설성
  hosts: all
  vars_files:
    - vars/var.yml
  tasks: 
    - name: 1) 방화벽 삭제 - {{ fw_80 }}, {{ fw_443 }}
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        immediate: true
        state: disabled
      loop:
        - "{{ fw_80 }}"
        - "{{ fw_443 }}"
    - name: 2) 서비스 종료 - {{ svc_web }}, {{ svc_fw }} 
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
      loop:
        - "{{ svc_web }}"
        - "{{ svc_fw }}"
    - name: 3) 설정 삭제- {{ indexfile }}
      ansible.builtin.file:
        path: "{{ indexfile }}"
        state: absent
    - name: 4) 패키지 삭제- {{ pkg_http_web }}, {{ pkg_https_web }}, {{ pkg_fw }}, {{ pkg_python }}
      ansible.builtin.dnf:
        name:
          - "{{ pkg_http_web }}"
          - "{{ pkg_https_web }}"
          - "{{ pkg_fw }}"
          - "{{ pkg_python }}"
        state: absent
